
ref:
  name: test
  # reference genome fasta file
  fasta: testdata/genome.fa
  # refernece genome gtf file
  gtf: testdata/genome.gtf

starrefdir: "_PATHTO_/starindex"

samples: "samples.tsv"
wdir: "mapping"
modes:
  - se
  - pe
pval-threshold: 1e-4
